"""create_tables

Revision ID: 41f0a89bd7a9
Revises: 
Create Date: 2026-06-30 15:47:56.924140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f0a89bd7a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ADMINISTRADOR', 'INSTRUTOR', 'ALUNO', name='tipousuario'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administrador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('instrutor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cref', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cref')
    )
    op.create_table('ficha_treino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objetivo', sa.String(length=200), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('instrutor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matricula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_treino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('ficha_treino_id', sa.UUID(), nullable=False),
    sa.Column('exercicio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('repeticoes > 0', name='ck_item_treino_repeticoes_positivas'),
    sa.CheckConstraint('series > 0', name='ck_item_treino_series_positivas'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['ficha_treino_id'], ['ficha_treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_treino')
    op.drop_table('matricula')
    op.drop_table('ficha_treino')
    op.drop_table('instrutor')
    op.drop_table('aluno')
    op.drop_table('administrador')
    op.drop_table('usuario')
    op.drop_table('exercicio')
    # ### end Alembic commands ###
