"""create ficha treino item treino exercicio

Revision ID: 6f66595d05da
Revises: 9117b35c9119
Create Date: 2026-06-28 17:34:00.535475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f66595d05da'
down_revision: Union[str, None] = '9117b35c9119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('ficha_treino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objetivo', sa.String(length=200), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('instrutor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_treino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('ficha_treino_id', sa.UUID(), nullable=False),
    sa.Column('exercicio_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('repeticoes > 0', name='ck_item_treino_repeticoes_positivas'),
    sa.CheckConstraint('series > 0', name='ck_item_treino_series_positivas'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['ficha_treino_id'], ['ficha_treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_treino')
    op.drop_table('ficha_treino')
    op.drop_table('exercicio')
    # ### end Alembic commands ###
