"""create_instrutor_aluno_e_matricula

Revision ID: 9117b35c9119
Revises: 
Create Date: 2026-06-26 13:18:00.689502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9117b35c9119'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ADMINISTRADOR', 'INSTRUTOR', 'ALUNO', name='tipousuario'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aluno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('instrutor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cref', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cref')
    )
    op.create_table('matricula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matricula')
    op.drop_table('instrutor')
    op.drop_table('aluno')
    op.drop_table('usuario')
    # ### end Alembic commands ###
